### ISSUE TITLE
missing files?  http://stsci.edu/schemas/jwst_datamodel/ramp.schema

### ISSUE THREAD

**Issue by aschuss** [spacetelescope/jwebbinar_prep#118] opened 2022-10-10 00:46 UTC
hi, thanks so much for providing these notebooks
for the jwst-data-products part 1-3 solutions the schema file is no longer at the url provided?
Unable to fetch schema from non-file URL: http://stsci.edu/schemas/jwst_datamodel/ramp.schema
Thanks.
- Adam
-

**Comment by aschuss** [comment] 2022-10-12 00:25
Hi Thanks for getting back to me!
Here is the error from jwst-data-products-part1 and part2 -solutions:
Appreciate your help!
Best, Adam

C.-Examining the pipeline products
<http://localhost:8888/notebooks/jwst-data-products-part2-solutions.ipynb#C.-Examining-the-pipeline-products>

Let's take a closer look at some data products. We've already explored
uncalibrated data in part 1. Now, let's take a look at the output products
for Stage 1 processing. As our first example, we can grab the rate and
rateints data products for the simulation we used in module 1. Looking
above, we can see that these types of data use the ImageModel and the
CubeModel, respectively.
In [6]:
1

# Load the integration-averaged data into a model (use: rate_image)

2

rate_image = datamodels.ImageModel(rate_file[1])

/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf.extensions plugin from package asdf-astropy==0.2.2
failed to load:

ContextualVersionConflict: (jsonschema 4.16.0
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('jsonschema<4.10.0,>=4.0.1'), {'asdf'})
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf.extensions plugin from package gwcs==0.18.2 failed
to load:

ContextualVersionConflict: (jsonschema 4.16.0
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('jsonschema<4.10.0,>=4.0.1'), {'asdf'})
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf.extensions plugin from package jwst==1.7.2 failed to
load:

VersionConflict: (certifi 2022.9.24
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('certifi==2022.5.18.1'))
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf_extensions plugin from package jwst==1.7.2 failed to
load:

VersionConflict: (certifi 2022.9.24
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('certifi==2022.5.18.1'))
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf_extensions plugin from package specutils==1.8.1
failed to load:

ContextualVersionConflict: (jsonschema 4.16.0
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('jsonschema<4.10.0,>=4.0.1'), {'asdf'})
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf_extensions plugin from package stpipe==0.4.2 failed
to load:

ContextualVersionConflict: (jsonschema 4.16.0
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('jsonschema<4.10.0,>=4.0.1'), {'asdf'})
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf_extensions plugin from package asdf==2.13.0 failed
to load:

VersionConflict: (jsonschema 4.16.0
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('jsonschema<4.10.0,>=4.0.1'))
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf.resource_mappings plugin from package
asdf-astropy==0.2.2 failed to load:

ContextualVersionConflict: (jsonschema 4.16.0
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('jsonschema<4.10.0,>=4.0.1'), {'asdf'})
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf.resource_mappings plugin from package
asdf-coordinates-schemas==0.1.0 failed to load:

ContextualVersionConflict: (jsonschema 4.16.0
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('jsonschema<4.10.0,>=4.0.1'), {'asdf'})
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf.resource_mappings plugin from package
asdf-wcs-schemas==0.1.1 failed to load:

ContextualVersionConflict: (jsonschema 4.16.0
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('jsonschema<4.10.0,>=4.0.1'), {'asdf'})
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf.resource_mappings plugin from package jwst==1.7.2
failed to load:

VersionConflict: (certifi 2022.9.24
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('certifi==2022.5.18.1'))
  warnings.warn(
/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/entry_points.py:46:
AsdfWarning: asdf.resource_mappings plugin from package asdf==2.13.0
failed to load:

VersionConflict: (jsonschema 4.16.0
(/Users/Adam/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages),
Requirement.parse('jsonschema<4.10.0,>=4.0.1'))
  warnings.warn(

---------------------------------------------------------------------------FileNotFoundError
                        Traceback (most recent call last)
Input In [6], in <cell line: 2>()      1 # Load the
integration-averaged data into a model (use: rate_image)----> 2
rate_image = datamodels.ImageModel(rate_file[1])

File ~/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/stdatamodels/model_base.py:174,
in DataModel.__init__(self, init, schema, memmap, pass_invalid_values,
strict_validation, validate_on_assignment, cast_fits_arrays,
validate_arrays, ignore_missing_extensions, **kwargs)    171
schema = _DEFAULT_SCHEMA    172     else:    173         # Create an
AsdfFile so we can use its resolver for loading schemas--> 174
schema = asdf_schema.load_schema(self.schema_url,
resolve_references=True)    176 self._schema =
mschema.merge_property_trees(schema)    178 # Provide the object as
context to other classes and functions

File ~/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/schema.py:431,
in load_schema(url, resolver, resolve_references, resolve_local_refs)
  426     resolver = extension.get_default_resolver()    428 # We want
to cache the work that went into constructing the schema, but
returning    429 # the same object is treacherous, because users who
mutate the result will not    430 # expect that they're changing the
schema everywhere.--> 431 return
copy.deepcopy(_load_schema_cached(url, resolver, resolve_references,
resolve_local_refs))

File ~/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/schema.py:478,
in _load_schema_cached(url, resolver, resolve_references,
resolve_local_refs)    475 @lru_cache    476 def
_load_schema_cached(url, resolver, resolve_references,
resolve_local_refs):    477     loader =
_make_schema_loader(resolver)--> 478     schema, url = loader(url)
480     if resolve_references or resolve_local_refs:    482
def resolve_refs(node, json_id):

File ~/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/schema.py:355,
in _make_schema_loader.<locals>.load_schema(url)    351     return
result, url    353 # If not, this must be a URL (or missing).  Fall
back to fetching    354 # the schema the old way:--> 355 return
_load_schema(url)

File ~/anaconda3/anaconda3/envs/jwebbinar/lib/python3.9/site-packages/asdf/schema.py:319,
in _load_schema(url)    316 @lru_cache    317 def _load_schema(url):
 318     if url.startswith("http://") or url.startswith("https://") or
url.startswith("asdf://"):--> 319         raise
FileNotFoundError("Unable to fetch schema from non-file URL: " + url)
  321     with generic_io.get_file(url) as fd:    322         if
isinstance(url, str) and url.endswith("json"):
FileNotFoundError: Unable to fetch schema from non-file URL:
http://stsci.edu/schemas/jwst_datamodel/image.schema

**Comment by themiyan** [comment] 2022-10-12 07:22
I have the same problem wit JWST 1.8.0

**Comment by bhilbert4** [comment] 2022-10-12 13:01
I saw a similar error in a recent question in the STScI Help Desk. In that case, there was some problem with the installed environment. Starting over and creating a new environment solved the problem. I think that's probably a good thing to try first.

**Comment by aschuss** [comment] 2022-10-12 13:28
Thanks.But that url points to a missing file .Has the schema file been moved ? Should we store it locally ? Is there an environment variable that needs to be set?On Oct 12, 2022, at 9:01 AM, Bryan Hilbert ***@***.***> wrote:﻿
I saw a similar error in a recent question in the STScI Help Desk. In that case, there was some problem with the installed environment. Starting over and creating a new environment solved the problem. I think that's probably a good thing to try first.

**Comment by aschuss** [comment] 2022-10-12 15:10
Thanks very much !  Sorry, I missed that.  Working now.
Appreciate your help :)

**Comment by camipacifici** [comment] 2022-10-12 15:36
Thank you Bryan for stepping in!
Since the problem is resolved, I will close the issue.

**Closed by camipacifici** 2022-10-12 15:36 UTC

**Comment by themiyan** [comment] 2022-10-13 00:07
This also worked for me: 
`pip install --upgrade --force-reinstall asdf`
saving the hassle of reinstalling a whole new env
